In [1]:
#Importing pandas library
import pandas as pd

import numpy as np

# Series

Series is like numpy arrays. But unlike numpy we can modify the index in series.

In [2]:
#creating a series
series_1 = pd.Series(data=['Formaline','Hygyne', 'Gokul'])
series_1

0    Formaline
1       Hygyne
2        Gokul
dtype: object

In [3]:
#customized index
series2 = pd.Series(data=['A','B','C','D','E'], index=[1,2,3,4,5])
series2

1    A
2    B
3    C
4    D
5    E
dtype: object

In [4]:
#passing a dictionary as series data
#it takes key as index and value as data
dict1 = {'index1':'Taranath',
        'index2':'Taradas',
        'index3':'Amarjibon'}
series3 = pd.Series(data=dict1)
series3

index1     Taranath
index2      Taradas
index3    Amarjibon
dtype: object

# Accessing data from a series

series_name[index]

In [5]:
series2[3]

'C'

In [6]:
series3['index3']

'Amarjibon'

In [7]:
series4 = pd.Series(data=[1,2,3,4,5], index=['a','b','c','d','e'])
print("series4 : \n", series4)

series5 = pd.Series(data=[10,5,3,4], index=['b','f','d','e'])
print("\nseries4 : \n", series5)

print("\nadding both : \n", series4+series5)

series4 : 
 a    1
b    2
c    3
d    4
e    5
dtype: int64

series4 : 
 b    10
f     5
d     3
e     4
dtype: int64

adding both : 
 a     NaN
b    12.0
c     NaN
d     7.0
e     9.0
f     NaN
dtype: float64


# DataFrame

*Collection of Serieses

In [8]:
#creating a dataframe 
from numpy.random import randint
arr1 = randint(2,10, size=(4,3))
print("data : ", arr1)
df = pd.DataFrame(arr1, [1,2,3,4], ['num1','num2','num3'])
df

data :  [[3 9 2]
 [3 2 8]
 [3 3 6]
 [4 6 4]]


num1  num2  num3
1     3     9     2
2     3     2     8
3     3     3     6
4     4     6     4

In [9]:
 #creating new column
df['num4'] = randint(1,34, size=4)
df

num1  num2  num3  num4
1     3     9     2    24
2     3     2     8     2
3     3     3     6    27
4     4     6     4    29

In [10]:
# creating a new row
df.loc[5] = randint(1,34, size=4)
df

num1  num2  num3  num4
1     3     9     2    24
2     3     2     8     2
3     3     3     6    27
4     4     6     4    29
5    18    22     2    30

In [11]:
#deleting a column
df1 = df.drop('num2', axis=1)
df1

num1  num3  num4
1     3     2    24
2     3     8     2
3     3     6    27
4     4     4    29
5    18     2    30

In [12]:
#deleting a row
df2 = df.drop(3, axis=0)
df2

num1  num2  num3  num4
1     3     9     2    24
2     3     2     8     2
4     4     6     4    29
5    18    22     2    30

In [13]:
df
# this deletes happens temporaritly, does no harm to original dataframe
# to make these permanent, add - "inplace=True" in parameter

num1  num2  num3  num4
1     3     9     2    24
2     3     2     8     2
3     3     3     6    27
4     4     6     4    29
5    18    22     2    30

In [14]:
df.drop('num3', axis=1, inplace=True)
df

num1  num2  num4
1     3     9    24
2     3     2     2
3     3     3    27
4     4     6    29
5    18    22    30

# Selecting 


In [15]:
#selecting a column 
df['num2']

1     9
2     2
3     3
4     6
5    22
Name: num2, dtype: int32

In [16]:
#selecting a row
df.loc[2]

num1    3
num2    2
num4    2
Name: 2, dtype: int32

In [17]:
# selecting a row by position 
# position counts as - 0,1,2,3 ...
df.iloc[1]

num1    3
num2    2
num4    2
Name: 2, dtype: int32

In [18]:
# selecting a cell 
# format1 - df[column_name][row_name]
df['num1'][5]

18

In [19]:
# format2 - dataframe_name.loc[row_name][column_name]
df.loc[5]['num1']

18

In [20]:
# we can put this as below format also
df.loc[5,'num4']

30

In [21]:
# selecting subset of a dataframe
# format - dataframe_name.loc[list of rows, list of columns]

df.loc[[1,3], ['num1', 'num4']]

num1  num4
1     3    24
3     3    27

In [22]:
# cannot use this reverse format
df[['num1', 'num4'],[1,3]]

TypeError: '(['num1', 'num4'], [1, 3])' is an invalid key

Conditional Selection

In [40]:
arr2 = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
print(arr2)
df3 = pd.DataFrame(arr2, [1,2,3,4], ['col1', 'col2', 'col3', 'col4'])
df3

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]


col1  col2  col3  col4
1     1     2     3     4
2     5     6     7     8
3     9    10    11    12
4    13    14    15    16

In [42]:
#Setting and condition

print("condition \n", df3>5)

print("\n")

print("df which have values more than 5 : \n", df3[df3>5])

condition 
     col1   col2   col3   col4
1  False  False  False  False
2  False   True   True   True
3   True   True   True   True
4   True   True   True   True


df which have values more than 5 : 
    col1  col2  col3  col4
1   NaN   NaN   NaN   NaN
2   NaN   6.0   7.0   8.0
3   9.0  10.0  11.0  12.0
4  13.0  14.0  15.0  16.0


In [53]:
# Select col3 with values more than 5
df3[df3>5]['col3']

1     NaN
2     7.0
3    11.0
4    15.0
Name: col3, dtype: float64

In [59]:
# Select col3 and col3 with values more than 5
df3[df3>5][['col3','col4']]

col3  col4
1   NaN   NaN
2   7.0   8.0
3  11.0  12.0
4  15.0  16.0

In [61]:
# Select col3 with values more than 5 and less than 10
df3[(df3>5) & (df3<10)][['col3','col4']]

#Note - if we have to put more than one condition, must use ()
#     - if we have to put more than one column name, must put them as a list(inside [])
# for and - & 
# for or - |

col3  col4
1   NaN   NaN
2   7.0   8.0
3   NaN   NaN
4   NaN   NaN

# Indexing

df_name.reset_index() - will reset the indices as 0,1,2,3... in spite of having customized indices

df_name.set_index(list fo column names) 

Trick: we can use split() method of string to avoid writing column of row names as list

In [87]:
df4 = pd.DataFrame(np.arange(153,275,5).reshape((5,5)), ['r1','r2','r3','r4','r5'], ['c1','c2','c3','c4','c5'])
df4

c1   c2   c3   c4   c5
r1  153  158  163  168  173
r2  178  183  188  193  198
r3  203  208  213  218  223
r4  228  233  238  243  248
r5  253  258  263  268  273

In [81]:
df5 = df4.reset_index()
# customized index is also there but we have a new default index
# this is not permanently happened to the dataframe
# for this, we cannot use previous indices to fetch data 
print("Dataframe with reset index \n", df5)
print("\nOriginal dataframe \n", df4)

Dataframe with reset index 
   index   c1   c2   c3   c4   c5
0    r1  153  158  163  168  173
1    r2  178  183  188  193  198
2    r3  203  208  213  218  223
3    r4  228  233  238  243  248
4    r5  253  258  263  268  273

Original dataframe 
      c1   c2   c3   c4   c5
r1  153  158  163  168  173
r2  178  183  188  193  198
r3  203  208  213  218  223
r4  228  233  238  243  248
r5  253  258  263  268  273


In [82]:
df5.loc['r2']

KeyError: 'r2'

In [86]:
df4.loc['r2']

c1    178
c2    183
c3    188
c4    193
c5    198
Name: r2, dtype: int32

In [101]:
#adding new index to df4
print("before adding new indices : \n",df4)
df4['new_index'] = 'p q r s t'.split()
df4.set_index('new_index')

# setting index will override the previous index, if you want them, save them somewhere

before adding new indices : 
      c1   c2   c3   c4   c5 new_index
r1  153  158  163  168  173         p
r2  178  183  188  193  198         q
r3  203  208  213  218  223         r
r4  228  233  238  243  248         s
r5  253  258  263  268  273         t


c1   c2   c3   c4   c5
new_index                         
p          153  158  163  168  173
q          178  183  188  193  198
r          203  208  213  218  223
s          228  233  238  243  248
t          253  258  263  268  273

In [105]:
df4.loc['p']

KeyError: 'p'